# Generated by Django 4.0.3 on 2022-04-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=100)),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problems')),
            ],
        ),
    ]
