# Generated by Django 4.0.3 on 2022-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
