# Generated by Django 4.0.3 on 2022-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='code',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='solutions',
            name='language',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
