# Generated by Django 4.0.3 on 2022-04-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemStatement', models.TextField(max_length=5000)),
                ('name', models.TextField(max_length=100)),
                ('category', models.TextField(max_length=10)),
            ],
        ),
    ]
