# Generated by Django 4.0.3 on 2022-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='category',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=32),
        ),
    ]
