# Generated by Django 4.0.3 on 2022-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_solutions_code_solutions_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.CharField(choices=[('RUN TIME ERROR', 'Run Time Error'), ('COMPILE TIME ERROR', 'Compile Time Error'), ('TIME LIMIT EXCEEDED', 'Time Limit Exceeded'), ('ACCEPTED', 'Accepted')], max_length=50, null=True),
        ),
    ]
