# Generated by Django 4.0.3 on 2022-05-27 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_solutions_verdict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutions',
            old_name='problemId',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='solutions',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='testcases',
            old_name='problemId',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='code',
        ),
        migrations.RemoveField(
            model_name='solutions',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='input',
        ),
        migrations.RemoveField(
            model_name='testcases',
            name='output',
        ),
        migrations.AddField(
            model_name='solutions',
            name='code_file_path',
            field=models.TextField(default='abc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutions',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcases',
            name='testcase',
            field=models.FileField(default=None, upload_to='testcases/2022-05-27_22-48-09'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solutions',
            name='verdict',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
