# Generated by Django 4.0.3 on 2022-04-19 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_problems_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('RUN TIME ERROR', 'Run Time Error'), ('COMPILE TIME ERROR', 'Compile Time Error'), ('TIME LIMIT EXCEEDED', 'Time Limit Exceeded'), ('ACCEPTED', 'Accepted')], max_length=50)),
                ('submitted', models.DateTimeField(auto_now=True)),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problems')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
